services:
  web:
    build:
      context: .
      dockerfile: backend.Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:80"

  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    env_file:
      - .env
    depends_on:
      - web
      - db


  dashboard:
    image: mher/flower:0.9.7
    command:
      - "--broker=redis://redis:6379/0"
    depends_on:
      - redis
      - worker
    ports:
      - "5555:5555"

  redis:
    image: redis:7-alpine
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - "redis:/data"

volumes:
  redis:
    driver: local
  postgres_data:
